version: "3.7"

services:
  app:
    image: node12:peanjs
    command: node server.js
    ports:
      - 3030:3030
    working_dir: /opt/pean.js
    volumes:
      - ./:/opt/peanjs
    environment:
      DB_HOST: peandb
      DB_LOGGING: 'true'
    depends_on:
      - solr

  peandb:
    image: postgres:10.14
    volumes:
      - pean-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mypean_dev

  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/peanjs

volumes:
  pean-data:
  solr_data:
